database:
  host: "localhost"
  port: 27017
  name: "stocks"
  uri: "mongodb://localhost:27017/"

data_fetching:
  start_date: "2020-01-01"
  stock_suffix: ".NS"
  min_data_points: 50
  prediction_history_years: 5
  max_stocks_to_fetch: 5
  future_prediction_days: 100

models:
  lstm:
    units: 50
    learning_rate: 0.01
    epochs: 10
    batch_size: 32
    test_split: 0.2
    time_steps: 60
  
  arima:
    train_split_ratio: 0.8
    order: [1, 1, 1]
    
  gcn:
    epochs: 100
    learning_rate: 0.1
    hidden_dim: 64
    test_split: 0.2
